# Generated by Django 5.0.6 on 2024-06-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enableusapp', '0002_therapistuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('sickness', models.TextField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('therapist', models.ManyToManyField(to='enableusapp.therapistuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
