# Generated by Django 5.0.6 on 2024-06-12 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enableusapp', '0003_alter_therapistuser_address_bookingform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='sickness',
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='therapist',
        ),
        migrations.AddField(
            model_name='bookingform',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enableusapp.therapistuser'),
        ),
    ]
