# Generated by Django 5.0.6 on 2024-06-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enableusapp', '0007_remove_booking_address_remove_booking_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
