# Generated by Django 5.0.6 on 2024-06-13 07:37

import enableusapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enableusapp', '0011_alter_therapistuser_speciality_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='patient_profile_img',
            field=models.ImageField(default='patients/default.png', upload_to=enableusapp.models.patient_img),
        ),
    ]
